# The URL the site will be built for
base_url = "https://simonguillot.com"
title = "Simon Guillot"
description = "Freelance Software Engineer | Machine Learning & Edge Computing"
theme = "bulma"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
og_image = "avatar.png"
copyright = "© 2021 Simon Guillot"
katex_enable = true
katex_auto_render = true
social_links = [
    { name = "Github", url = "https://github.com/notsimon" },
    { name = "Linkedin", url = "https://www.linkedin.com/in/simon-guillot-302567184/" }
]

# extra_links = [
#     { title = "Products", links = [
#         { name = "Thoughtwriter", url = "https://simonguillot.com/thoughtwriter" },
#     ]}
# ]
